#if !defined(DEFINE_ANIM) || !defined(ADD_ANIM_FRAME)
#error fail including animations.h

#else


DEFINE_ANIM(ANIM_HERO1_WALK_DOWN)
	ADD_ANIM_FRAME(BITMAP_HERO1_NORMAL_DOWN, 100)
	ADD_ANIM_FRAME(BITMAP_HERO1_WALK1_DOWN, 100)
	ADD_ANIM_FRAME(BITMAP_HERO1_WALK2_DOWN, 100)
	ADD_ANIM_FRAME(BITMAP_HERO1_WALK3_DOWN, 100)
	ADD_ANIM_FRAME(BITMAP_HERO1_NORMAL_DOWN, 0)


#endif
